# Generated by Django 3.2.14 on 2023-08-30 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertransaction',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='usertransaction',
            name='user',
        ),
        migrations.AddField(
            model_name='usertransaction',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='owner_transactions', to='core.user', verbose_name='Отправитель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertransaction',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='recipient_transactions', to='core.user', verbose_name='Получатель'),
            preserve_default=False,
        ),
    ]
