# Generated by Django 3.2.14 on 2023-08-30 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230830_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransaction',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
    ]
